# Site settings
title: Janto's World
email: wztboyking@gmail.com
description: > # 这个博客以后用来记录一些学习笔记
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://wztboyking.github.com" # the base hostname & protocol for your site
github_username:  wztboyking
# https://github.com/wztboyking/demo.git

# Build settings
markdown: kramdown
